### ISSUE TITLE
`TypeDecoder` doesn't work on Android since v4.12.1

### ISSUE THREAD

**Issue by kamilargent** [hyperledger-web3j/web3j#2123]
# `TypeDecoder` doesn't work on Android since v4.12.1

## Steps To Reproduce
Try parsing events that includes numeric types using ABI

### Expected behavior
The type is decoded properly

### Actual behavior
Exception is thrown

## Environment
- Web3j version - v4.12.1 
- Android 10

## Additional context
Due to refactoring done in v4.12.1, the `TypeDecoder` uses Java 9 API that is not available on Android.

```
Caused by: java.lang.NoSuchMethodError: No direct method <init>(I[BII)V in class Ljava/math/BigInteger; or its super classes (declaration of 'java.math.BigInteger' appears in /apex/com.android.runtime/javalib/core-libart.jar)
21:34:01.607                                 E  	at org.web3j.abi.TypeDecoder.decodeNumeric(TypeDecoder.java:154)
21:34:01.607                                 E  	at org.web3j.abi.TypeDecoder.decode(TypeDecoder.java:114)
21:34:01.607                                 E  	at org.web3j.abi.TypeDecoder.decodeUintAsInt(TypeDecoder.java:296)
21:34:01.607                                 E  	at org.web3j.abi.DefaultFunctionReturnDecoder.getDataOffset(DefaultFunctionReturnDecoder.java:167)
21:34:01.607                                 E  	at org.web3j.abi.DefaultFunctionReturnDecoder.build(DefaultFunctionReturnDecoder.java:86)
21:34:01.607                                 E  	at org.web3j.abi.DefaultFunctionReturnDecoder.decodeFunctionResult(DefaultFunctionReturnDecoder.java:52)
21:34:01.607                                 E  	at org.web3j.abi.FunctionReturnDecoder.decode(FunctionReturnDecoder.java:57)
21:34:01.607                                 E  	at org.web3j.tx.Contract.staticExtractEventParameters(Contract.java:800)
21:34:01.607                                 E  	at org.web3j.tx.Contract.staticExtractEventParametersWithLog(Contract.java:833)
21:34:01.607                                 E  	at org.web3j.tx.Contract.extractEventParametersWithLog(Contract.java:829)
21:34:01.607                                 E  	at org.web3j.tx.Contract.lambda$extractEventParametersWithLog$12(Contract.java:840)
21:34:01.607                                 E  	at org.web3j.tx.Contract.$r8$lambda$uLi88uv0h6UqGgbBPxkUMD-ynwA(Unknown Source:0)
21:34:01.607                                 E  	at org.web3j.tx.Contract$$ExternalSyntheticLambda12.apply(D8$$SyntheticClass:0)
21:34:01.607                                 E  	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:222)
21:34:01.607                                 E  	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
21:34:01.607                                 E  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:501)
21:34:01.607                                 E  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:491)
21:34:01.607                                 E  	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
21:34:01.607                                 E  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:252)
21:34:01.607                                 E  	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:560)
21:34:01.607                                 E  	at org.web3j.tx.Contract.extractEventParametersWithLog(Contract.java:842)
```

**Comment by aceppaluni** [comment]
Hi, Can I take this on?

**Comment by aceppaluni** [comment]
Upon investigation and testing, issue seems to be resolved. Attempted to reproduce issue and run test through Android Studio. Test results coming back clean for parsing numeric types. After research, JDK version being used is 21 and does not conflict as Java 9 is now supported.

**Comment by aceppaluni** [comment]
<img width="955" alt="Image" src="https://github.com/user-attachments/assets/407e1950-5804-4edc-b4e8-0c4c9edace5a" />
